import pandas as pd

CURRENT_YEAR = 2025

def dur(start, end):
	year_end = CURRENT_YEAR if end == "Present" else end
	return year_end - start

rows = []

def add(territory, region, start, end, status, notes):
	rows.append({
		"territory": territory,
		"region": region,
		"start": start,
		"end": end,
		"status": status,
		"notes": notes,
		"duration_years": dur(start, end)
	})

# Core England/Wessex & absorbed polities (obscure included)
add("Wessex (as core of the English Crown)", "Britain & Ireland", 519, "Present", "Merged into English Crown", "Founding of Wessex by Cerdic")
add("Kent (kingdom absorbed)", "Britain & Ireland", 825, "Present", "County of England", "Permanent Wessex control post-825")
add("Sussex (kingdom absorbed)", "Britain & Ireland", 827, "Present", "Historic county of England", "Absorbed by Wessex early 9th c.")
add("Essex (kingdom absorbed)", "Britain & Ireland", 825, "Present", "Historic county of England", "Under Wessex/English Crown after Mercian eclipse")
add("East Anglia (kingdom absorbed)", "Britain & Ireland", 918, "Present", "Historic region", "Edward the Elder control by 918")
add("Mercia (kingdom absorbed)", "Britain & Ireland", 918, "Present", "Historic region", "Unified by Edward the Elder 918")
add("Northumbria (incl. Deira & Bernicia, absorbed)", "Britain & Ireland", 954, "Present", "Historic region", "After 954 into English Crown")
add("Hwicce (sub-kingdom)", "Britain & Ireland", 680, "Present", "Historic region", "Gradual absorption into Mercia then England")
add("Lindsey (sub-kingdom)", "Britain & Ireland", 700, "Present", "Historic region", "Absorbed into Mercia/England (approx. 7th–8th c.)")
add("Magonsæte (sub-kingdom)", "Britain & Ireland", 700, "Present", "Historic region", "Absorbed into Mercia/England (approx.)")
add("Middle Anglia (sub-kingdom)", "Britain & Ireland", 700, "Present", "Historic region", "Absorbed into Mercia/England (approx.)")
add("Cornwall (Dumnonia)", "Britain & Ireland", 838, "Present", "Historic county of England", "Overlordship after Hingston Down")
add("Wales", "Britain & Ireland", 1284, "Present", "Constituent country of UK", "Statute of Rhuddlan; integrated 1536–1543")
add("Channel Islands (Jersey, Guernsey, Sark, Alderney)", "Crown Dependencies", 1204, "Present", "Crown Dependencies", "Retained after loss of Normandy mainland")
add("Isle of Man", "Crown Dependencies", 1399, "Present", "Crown Dependency", "Crown lordship from 1399; revested 1765")
add("Scotland", "Britain & Ireland", 1603, "Present", "Constituent country of UK", "Union of the Crowns 1603; Acts of Union 1707")

# Ireland and Northern Ireland (continuous rule over land)
add("Ireland (whole island under the Crown)", "Britain & Ireland", 1171, 1949, "Former kingdom within UK", "Lordship 1171; Kingdom 1542; UK 1801–1922")
add("Ulster / Northern Ireland area", "Britain & Ireland", 1171, "Present", "Constituent part of UK", "Continuity of Crown rule in the north to present")

# Commonwealth realms (ensure Present continuity)
add("Newfoundland (now Canadian province)", "Commonwealth Realms", 1583, "Present", "Part of Canada (realm)", "Colony 1583; Dominion 1907; into Canada 1949; Crown continuity")
add("Nova Scotia (now Canadian province)", "Commonwealth Realms", 1713, "Present", "Part of Canada (realm)", "Treaty of Utrecht 1713; Crown continuity")
add("Quebec / Canada East (now Quebec)", "Commonwealth Realms", 1763, "Present", "Part of Canada (realm)", "Crown since 1763; continuity")
add("Ontario (Upper Canada/Canada West, now Ontario)", "Commonwealth Realms", 1791, "Present", "Part of Canada (realm)", "Created 1791; continuity")
add("Prince Edward Island", "Commonwealth Realms", 1769, "Present", "Part of Canada (realm)", "Crown since 1769; joined 1873")
add("New Brunswick", "Commonwealth Realms", 1784, "Present", "Part of Canada (realm)", "Separated 1784; continuity")
add("British Columbia (incl. Vancouver Island)", "Commonwealth Realms", 1849, "Present", "Part of Canada (realm)", "Vancouver Island 1849; BC 1858; continuity")
add("Manitoba (Red River area)", "Commonwealth Realms", 1812, "Present", "Part of Canada (realm)", "Selkirk settlement/HBC; to Canada 1870")
add("Saskatchewan (NWT portions)", "Commonwealth Realms", 1870, "Present", "Part of Canada (realm)", "From Rupert's Land/NWT 1870; continuity")
add("Alberta (NWT portions)", "Commonwealth Realms", 1870, "Present", "Part of Canada (realm)", "From Rupert's Land/NWT 1870; continuity")
add("Yukon", "Commonwealth Realms", 1898, "Present", "Part of Canada (realm)", "Created 1898; continuity")
add("Northwest Territories", "Commonwealth Realms", 1870, "Present", "Part of Canada (realm)", "Transferred 1870; continuity")
add("Nunavut", "Commonwealth Realms", 1999, "Present", "Part of Canada (realm)", "Created 1999; continuity")
add("Rupert's Land & North-Western Territory (HBC chartered)", "Commonwealth Realms", 1670, "Present", "Now within Canada (realm)", "Ceded to Canada 1870; Crown continuity via realm")

add("New South Wales", "Commonwealth Realms", 1788, "Present", "State of Australia (realm)", "Continuity under Crown")
add("Tasmania (Van Diemen's Land)", "Commonwealth Realms", 1803, "Present", "State of Australia (realm)", "Continuity under Crown")
add("Victoria", "Commonwealth Realms", 1851, "Present", "State of Australia (realm)", "Continuity under Crown")
add("Queensland", "Commonwealth Realms", 1859, "Present", "State of Australia (realm)", "Continuity under Crown")
add("South Australia", "Commonwealth Realms", 1836, "Present", "State of Australia (realm)", "Continuity under Crown")
add("Western Australia", "Commonwealth Realms", 1829, "Present", "State of Australia (realm)", "Continuity under Crown")
add("Northern Territory", "Commonwealth Realms", 1863, "Present", "Territory of Australia (realm)", "Continuity under Crown")
add("Australian Capital Territory", "Commonwealth Realms", 1911, "Present", "Territory of Australia (realm)", "Continuity under Crown")

add("New Zealand (realm)", "Commonwealth Realms", 1840, "Present", "Sovereign realm", "Treaty of Waitangi 1840; continuity")

add("Jamaica (realm)", "Commonwealth Realms", 1655, "Present", "Sovereign realm", "Conquered 1655; realm since 1962")
add("The Bahamas (realm)", "Commonwealth Realms", 1718, "Present", "Sovereign realm", "Crown colony 1718; realm since 1973")
add("Belize (realm)", "Commonwealth Realms", 1862, "Present", "Sovereign realm", "Colony 1862; realm since 1981")
add("Grenada (realm)", "Commonwealth Realms", 1762, "Present", "Sovereign realm", "British from 1762; realm since 1974")
add("Saint Lucia (realm)", "Commonwealth Realms", 1803, "Present", "Sovereign realm", "British from 1803; realm since 1979")
add("Saint Vincent and the Grenadines (realm)", "Commonwealth Realms", 1763, "Present", "Sovereign realm", "Realm since 1979")
add("Antigua and Barbuda (realm)", "Commonwealth Realms", 1632, "Present", "Sovereign realm", "Realm since 1981")
add("Saint Kitts and Nevis (realm)", "Commonwealth Realms", 1623, "Present", "Sovereign realm", "Realm since 1983")
add("Papua New Guinea (realm)", "Commonwealth Realms", 1884, "Present", "Sovereign realm", "British New Guinea 1884 (via Aus); realm since 1975")
add("Solomon Islands (realm)", "Commonwealth Realms", 1893, "Present", "Sovereign realm", "Protectorate 1893; realm 1978")
add("Tuvalu (realm)", "Commonwealth Realms", 1892, "Present", "Sovereign realm", "Protectorate era; realm 1978")
add("Barbados", "Caribbean (former realm)", 1627, 2021, "Republic since 2021", "Ended 2021")

# Crown Dependencies & Overseas Territories (present)
add("Gibraltar", "Overseas Territories", 1704, "Present", "Overseas Territory", "Captured 1704; ceded 1713")
add("Bermuda", "Overseas Territories", 1609, "Present", "Overseas Territory", "Settled 1609; colony from 1684")
add("Falkland Islands", "Overseas Territories", 1833, "Present", "Overseas Territory", "Reasserted 1833")
add("Saint Helena, Ascension and Tristan da Cunha", "Overseas Territories", 1659, "Present", "Overseas Territory", "EIC then Crown; continuous")
add("Cayman Islands", "Overseas Territories", 1670, "Present", "Overseas Territory", "Madrid 1670")
add("Montserrat", "Overseas Territories", 1632, "Present", "Overseas Territory", "English colony 1632")
add("Turks and Caicos Islands", "Overseas Territories", 1799, "Present", "Overseas Territory", "Annexed 1799; separate 1848")
add("British Virgin Islands", "Overseas Territories", 1672, "Present", "Overseas Territory", "Captured from Dutch 1672")
add("Anguilla", "Overseas Territories", 1650, "Present", "Overseas Territory", "First settled 1650; separate 1980")
add("Pitcairn Islands", "Overseas Territories", 1838, "Present", "Overseas Territory", "Annexed 1838")
add("South Georgia & South Sandwich Islands", "Overseas Territories", 1908, "Present", "Overseas Territory", "Letters patent 1908")
add("SBA Akrotiri and Dhekelia (Cyprus)", "Overseas Territories", 1960, "Present", "Sovereign Base Areas", "Retained 1960")
add("British Indian Ocean Territory", "Overseas Territories", 1965, "Present", "Overseas Territory", "Formed 1965")
add("British Antarctic Territory", "Overseas Territories", 1962, "Present", "Overseas Territory", "Claim subject to treaty suspension")

# Europe & Mediterranean historical (Angevin etc.)
add("Duchy of Normandy (continental parts)", "Europe (Angevin/Plantagenet)", 1066, 1204, "Lost to France", "Plantagenet rule as Duke/King")
add("Duchy of Aquitaine / Guyenne / Gascony", "Europe (Angevin/Plantagenet)", 1154, 1453, "Lost to France", "Held by English Crown 1154–1453")
add("County/Duchy of Anjou", "Europe (Angevin/Plantagenet)", 1154, 1204, "Lost to France", "Plantagenet patrimony")
add("County of Maine", "Europe (Angevin/Plantagenet)", 1154, 1204, "Lost to France", "Plantagenet patrimony")
add("County of Touraine", "Europe (Angevin/Plantagenet)", 1154, 1204, "Lost to France", "Plantagenet patrimony")
add("County of Poitou", "Europe (Angevin/Plantagenet)", 1154, 1204, "Lost to France", "Plantagenet patrimony")
add("Pale of Calais (Calaisis)", "Europe (Hundred Years' War)", 1347, 1558, "Lost to France", "English enclave 1347–1558")
add("Dunkirk & Mardyke", "Europe (Protectorate era)", 1658, 1662, "Sold to France 1662", "Held after Treaty of the Pyrenees via Spain")
add("Tangier (now Morocco)", "North Africa", 1661, 1684, "Abandoned 1684", "Part of Catherine of Braganza dowry")
add("Menorca (periods of British rule)", "Europe & Mediterranean", 1708, 1802, "Returned to Spain", "Held 1708–1756, 1763–1782, 1798–1802")
add("Gibraltar (listed)", "Europe & Mediterranean", 1704, "Present", "Overseas Territory", "As above")
add("Malta", "Europe & Mediterranean", 1814, 1964, "Republic (1974)", "British from 1814; independence 1964")
add("Ionian Islands (United States under British protection)", "Europe & Mediterranean", 1815, 1864, "United with Greece", "British protectorate 1815–1864")
add("Heligoland", "Europe & North Sea", 1807, 1890, "Ceded to Germany", "From Denmark 1807; ceded 1890")
add("Hanover (personal union)", "Germany", 1714, 1837, "Ended with Salic law succession", "Personal union with British Crown")

# Military occupations & administrations (WWI/WWII and others)
add("Rhineland (British zone of occupation)", "Germany (WWI)", 1919, 1926, "Occupation ended 1926", "British Army of the Rhine around Cologne")
add("British Zone of Germany", "Germany (WWII)", 1945, 1949, "Became Federal Republic zones", "NW Germany under British occupation")
add("Berlin British Sector", "Germany (WWII)", 1945, 1990, "Unified Germany 1990", "British sector in Berlin")
add("Allied-occupied Austria (British zone)", "Austria (WWII)", 1945, 1955, "State Treaty 1955", "British zone incl. Styria/Carinthia portions")
add("Cyrenaica (British Military Administration)", "Libya (WWII)", 1943, 1951, "Kingdom of Libya 1951", "BMA Cyrenaica")
add("Tripolitania (British Military Administration)", "Libya (WWII)", 1943, 1951, "Kingdom of Libya 1951", "BMA Tripolitania")
add("Eritrea (British Military Administration)", "Horn of Africa (WWII)", 1941, 1952, "Federated with Ethiopia 1952", "BMA Eritrea")
add("Italian Somaliland (BMA)", "Horn of Africa (WWII)", 1941, 1950, "UN Trust to Italy 1950", "British administration 1941–1950")
add("Dodecanese Islands (Allied military government)", "Aegean (WWII)", 1945, 1947, "To Greece 1947", "British-administered AMG 1945–1947")
add("Allied military government in Italy (British-administered areas)", "Italy (WWII)", 1943, 1947, "Treaty of Peace 1947", "AMGOT/ACC in southern/central areas")
add("Constantinople / Istanbul (Allied occupation)", "Ottoman Empire (WWI)", 1918, 1923, "Ended 1923", "British presence in Allied occupation")

# Middle East & South Asia (Crown & protectorates)
add("Aden Colony", "Middle East & North Africa", 1839, 1967, "Part of Yemen", "Colony 1839–1967")
add("Aden Protectorate (Eastern & Western)", "Middle East & North Africa", 1886, 1967, "South Yemen 1967", "Protectorates via treaties")
add("Protectorate of South Arabia (Federation)", "Middle East & North Africa", 1962, 1967, "South Yemen 1967", "Reorganisation of Aden protectorates")
add("Egypt (occupation/influence)", "Middle East & North Africa", 1882, 1956, "Ended with Suez withdrawal", "Occupation 1882; formal protectorate 1914–1922")
add("Sudan (Anglo-Egyptian)", "Middle East & North Africa", 1899, 1956, "Republic 1956", "Condominium rule")
add("Iraq (British Mandate)", "Middle East & North Africa", 1920, 1932, "Kingdom 1932", "League of Nations Mandate")
add("Transjordan (Jordan)", "Middle East & North Africa", 1921, 1946, "Independence 1946", "British protectorate to 1946")
add("Palestine (Mandate)", "Middle East & North Africa", 1920, 1948, "Mandate ended 1948", "League of Nations Mandate")
add("Kuwait (protectorate)", "Middle East & North Africa", 1899, 1961, "State of Kuwait", "Anglo-Kuwaiti Agreement 1899")
add("Qatar (protectorate)", "Middle East & North Africa", 1916, 1971, "State of Qatar", "Protectorate 1916–1971")
add("Bahrain (protectorate)", "Middle East & North Africa", 1861, 1971, "Kingdom of Bahrain", "Protectorate 1861–1971")
add("Trucial States (now UAE)", "Middle East & North Africa", 1820, 1971, "United Arab Emirates", "Treaty system 1820–1971")
add("Oman (treaty influence)", "Middle East & North Africa", 1798, 1970, "Sultanate of Oman", "Close British influence")

# South Asia core
add("Bengal Presidency (under Crown)", "South Asia", 1690, 1950, "Province in British India", "English settlement at Calcutta 1690; Crown from 1858")
add("Bombay Presidency (under Crown)", "South Asia", 1661, 1950, "Province in British India", "Bombay ceded 1661; to EIC 1668; Crown from 1858")
add("Madras Presidency (under Crown)", "South Asia", 1640, 1950, "Province in British India", "Fort St George 1640; Crown from 1858")
add("Burma / Myanmar (as province and colony)", "South Asia", 1824, 1948, "Independent 1948", "Annexations 1824–86; separated from India 1937")
add("Ceylon / Sri Lanka (dominion)", "South Asia", 1796, 1972, "Republic 1972", "British from 1796; Kandyan Convention 1815")

add("Bengal (India)", "South Asia", 1690, 1950, "Former province/region", "From English settlement at Calcutta 1690; Crown to 1950")
add("Bengal (Pakistan; East Bengal/East Pakistan)", "South Asia", 1690, 1956, "Former province/region", "Continuity under Pakistan dominion to 1956")
add("Punjab (India)", "South Asia", 1849, 1950, "Former province/region", "Annexed after Anglo-Sikh Wars; Crown to 1950")
add("Punjab (Pakistan)", "South Asia", 1849, 1956, "Former province/region", "Annexed after Anglo-Sikh Wars; Crown to 1956")
add("Sindh (Pakistan)", "South Asia", 1843, 1956, "Former province/region", "Annexed 1843; Crown to 1956")
add("North-West Frontier Province / Khyber Pakhtunkhwa (Pakistan)", "South Asia", 1901, 1956, "Former province/region", "NWFP created 1901; Crown to 1956")
add("Baluchistan (Pakistan)", "South Asia", 1876, 1956, "Former province/region", "Treaties from 1876; Crown to 1956")
add("Assam (India)", "South Asia", 1826, 1950, "Former province/region", "Treaty of Yandabo 1826; Crown to 1950")
add("Hyderabad (India)", "South Asia", 1798, 1950, "Princely state under paramountcy", "Subsidiary Alliance 1798; Crown to 1950")
add("Mysore (India)", "South Asia", 1799, 1950, "Princely state under paramountcy", "Subsidiary Alliance 1799; Crown to 1950")
add("Kashmir (Pakistan-administered areas)", "South Asia", 1846, 1956, "Princely state under paramountcy", "Treaty of Amritsar 1846; Crown to 1956")
add("Bahawalpur (Pakistan)", "South Asia", 1833, 1956, "Princely state under paramountcy", "Treaty 1833; acceded to Pakistan; Crown to 1956")

# Southeast & East Asia (beyond already added)
add("Straits Settlements", "Southeast Asia", 1826, 1946, "Dissolved 1946", "Singapore, Penang, Malacca")
add("Federated Malay States", "Southeast Asia", 1895, 1946, "Reorganised 1946", "Protected states with Residents")
add("Unfederated Malay States", "Southeast Asia", 1909, 1946, "Reorganised 1946", "Protectorates via Anglo-Siamese Treaty")
add("Malaya / Federation of Malaya", "Southeast Asia", 1946, 1957, "Malaysia 1963", "Union then Federation")
add("North Borneo (Sabah)", "Southeast Asia", 1888, 1963, "Malaysia 1963", "Protectorate then colony")
add("Sarawak", "Southeast Asia", 1888, 1963, "Malaysia 1963", "Protectorate then colony")
add("Singapore (as colony/state)", "Southeast Asia", 1946, 1965, "Republic 1965", "Post-Straits period")
add("Hong Kong (Island & Kowloon)", "East Asia", 1842, 1997, "Returned to China", "Treaty cessions")
add("New Territories (HK lease)", "East Asia", 1898, 1997, "Lease expired", "99-year lease")

# Africa (colonies/protectorates/mandates)
add("Cape Colony / Cape Province", "Africa", 1806, 1961, "Union of South Africa", "British from 1806")
add("Natal", "Africa", 1843, 1961, "Union of South Africa", "Annexed 1843")
add("Orange River Colony", "Africa", 1900, 1961, "Union of South Africa", "After Boer War")
add("Transvaal Colony", "Africa", 1902, 1961, "Union of South Africa", "After Boer War")
add("Southern Rhodesia (Zimbabwe)", "Africa", 1923, 1980, "Republic 1980", "Self-governing colony")
add("Northern Rhodesia (Zambia)", "Africa", 1924, 1964, "Republic 1964", "Protectorate/colony")
add("Nyasaland (Malawi)", "Africa", 1891, 1964, "Republic 1964", "Protectorate")
add("Bechuanaland (Botswana)", "Africa", 1885, 1966, "Republic 1966", "Protectorate")
add("Basutoland (Lesotho)", "Africa", 1868, 1966, "Kingdom 1966", "Protectorate")
add("Swaziland / Eswatini", "Africa", 1903, 1968, "Kingdom 1968", "Protectorate")
add("Gold Coast (Ghana)", "Africa", 1664, 1960, "Republic 1960", "English forts from 1664; Crown colony from 1821")
add("The Gambia", "Africa", 1661, 1970, "Republic 1970", "St Andrew's Island/James Island from 1661; Crown colony 1888")
add("Nigeria (Colony & Protectorate)", "Africa", 1861, 1960, "Republic 1963", "Lagos annexed 1861; protectorates 1880s–1900; amalgamation 1914")
add("Sierra Leone", "Africa", 1808, 1971, "Republic 1971", "Crown colony 1808")
add("British Cameroons (Mandate/Trust)", "Africa", 1922, 1961, "Partitioned 1961", "Parts joined Nigeria/Cameroon")
add("British Togoland (Mandate/Trust)", "Africa", 1922, 1957, "United with Ghana", "Mandate/trust territory")
add("Kenya (Colony & Protectorate)", "Africa", 1895, 1964, "Republic 1964", "Protectorate 1895; colony 1920")
add("Uganda Protectorate", "Africa", 1894, 1963, "Republic 1963", "Protectorate")
add("Tanganyika (Mandate/Trust)", "Africa", 1919, 1964, "United with Zanzibar 1964", "Mandate/trust")
add("Zanzibar Protectorate", "Africa", 1890, 1963, "Union with Tanganyika", "Protectorate 1890–1963")
add("British Somaliland Protectorate", "Africa", 1884, 1960, "United with Italian Somalia", "Protectorate 1884–1960")
add("Egypt (protectorate period)", "Africa", 1914, 1922, "Ended protectorate", "Formal protectorate WWI")

# Americas extras
add("Trinidad and Tobago", "Caribbean", 1797, 1976, "Republic 1976", "Crown colony 1802")
add("Guyana (British Guiana)", "Americas", 1814, 1960, "Republic 1970", "From Dutch colonies 1814")
add("Bay Islands (Honduras)", "Americas", 1852, 1860, "Returned to Honduras", "Short-lived colony")
add("Mosquito Coast (Protectorate)", "Americas", 1844, 1860, "Protectorate ended 1860", "British protectorate on Nicaraguan coast")

# Atlantic outposts (already included via OT group but kept here for granularity)
add("Ascension Island", "Atlantic", 1815, "Present", "Part of St Helena etc.", "Garrisoned 1815; continuous")
add("Tristan da Cunha", "Atlantic", 1816, "Present", "Part of St Helena etc.", "Annexed 1816; continuous")
add("South Georgia", "South Atlantic", 1908, "Present", "Part of SGSSI", "Letters patent 1908")

# Americas extras
add("Virginia (colony)", "Americas (Thirteen Colonies)", 1607, 1783, "Former colony", "First permanent English colony in North America")
add("Massachusetts (colony → province)", "Americas (Thirteen Colonies)", 1628, 1783, "Former colony", "Massachusetts Bay 1628; Province from 1691")
add("New Hampshire", "Americas (Thirteen Colonies)", 1629, 1783, "Former colony", "Early grants 1629; royal province from 1679")
add("Connecticut", "Americas (Thirteen Colonies)", 1636, 1783, "Former colony", "Charter colony from 1662")
add("Rhode Island", "Americas (Thirteen Colonies)", 1636, 1783, "Former colony", "Charter colony from 1663")
add("Maryland", "Americas (Thirteen Colonies)", 1632, 1783, "Former colony", "Proprietary colony from 1632")
add("New York", "Americas (Thirteen Colonies)", 1664, 1783, "Former colony", "Captured from Dutch 1664")
add("New Jersey", "Americas (Thirteen Colonies)", 1664, 1783, "Former colony", "Proprietary then royal colony")
add("Delaware", "Americas (Thirteen Colonies)", 1664, 1783, "Former colony", "Under English rule from 1664; separate assembly from 1704")
add("Pennsylvania", "Americas (Thirteen Colonies)", 1681, 1783, "Former colony", "Proprietary colony from 1681")
add("North Carolina", "Americas (Thirteen Colonies)", 1663, 1783, "Former colony", "Separated as distinct colony by 1712")
add("South Carolina", "Americas (Thirteen Colonies)", 1663, 1783, "Former colony", "Separated as distinct colony by 1712")
add("Georgia", "Americas (Thirteen Colonies)", 1732, 1783, "Former colony", "Trusteeship from 1732; royal from 1752")
add("Florida (British period)", "Americas (Thirteen Colonies)", 1763, 1783, "Returned to Spain", "Acquired from Spain 1763; ceded back 1783")
add("Louisiana (British period)", "Americas (Thirteen Colonies)", 1763, 1783, "Returned to France", "Acquired from Spain 1763; ceded back 1783")

# Save and display
df = pd.DataFrame(rows)
df_sorted = df.sort_values(by=["duration_years","territory"], ascending=[False, True]).reset_index(drop=True)

csv_path = "C:/Desktop/british_crown_territories_ranked_2025.csv"
df_sorted.to_csv(csv_path, index=False)

csv_path