import api from '../api';
import { FaStickyNote, FaSpinner } from 'react-icons/fa';
import { useState } from 'react';

const ContextButton = ({ post, isExternal = false, hasMembership, showNote, setShowNote, note, setNote, setIsMisinfo, setPostErrorMessage, setShowMembershipModal }) => {
    const [isLoading, setIsLoading] = useState(false);

    const handleClick = async () => {
        if (!hasMembership) {
            setShowMembershipModal(true);
            return;
        }
        try {
            if (showNote) {
                setShowNote(false);
            } else if (note) {
                setShowNote(true);
            } else {
                setIsLoading(true);
                const textContent = post?.text_body || '';
                const postContent = `${post?.title ? 'Title: ' + post.title + '\n' : ''}${textContent}`;
                const postId = post?.post_id;
                const response = await api.post('/context_button', {
                    postContent,
                    postId,
                    isExternal
                });
                if (response.status === 202) {
                    //Note is being generated by another process, poll for it
                    setPostErrorMessage("Note is being generated, try again shortly.");
                    setTimeout(() => { setPostErrorMessage(''); }, 5000);
                    return;
                }
                const { newNote } = response.data;
                setNote(newNote.note_content);
                if (newNote.is_misinfo) {
                    setIsMisinfo(true);
                }
                setShowNote(true);
            }
        } catch (error) {
            if (error.response?.status === 403) {
                setShowMembershipModal(true);
            } else {
                setPostErrorMessage("Error getting context.");
                setTimeout(() => { setPostErrorMessage(''); }, 5000);
            }
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <button
            className="large-icon"
            disabled={isLoading}
            onClick={handleClick}
            title={showNote ? 'Close context' : isLoading ? 'Loading...' : 'Additional context'}
            style={{ opacity: isLoading ? 0.5 : 1 }}
        >
            {isLoading ? <FaSpinner style={{ animation: 'spin 1s linear infinite' }} /> : <FaStickyNote />}
        </button>
    );
};

export default ContextButton;
