const ALGORITHM_TEMPLATES = {
    "breaking_news": {
        name: "Breaking News",
        chronology: 0.9, 
        sentiment: 0,
        variety: 0.9,
        voteImpact: 0.8,
        minWords: 10,
        maxWords: null,
        minVideo: 0,
        maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "breaking,news,update,urgent,developing,alert,live,happening,latest,confirmed",
        wordSuppress: "rumor,unconfirmed,speculation,allegedly,reportedly",
        customInstruction: "Show verified breaking news and current events. Prioritise recent posts with high engagement and visual content. Suppress unconfirmed information."
    },
    "shortform_viral": {
        name: "Shortform", 
        chronology: 0.8,
        sentiment: 0.4,
        variety: 0.9,
        voteImpact: 0.7,
        minWords: 0,
        maxWords: 120,
        minVideo: 0,
        maxVideo: 60,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "viral,trending,quick,tip,hack,wow,amazing,genius,simple,fast",
        wordSuppress: "long,detailed,comprehensive,analysis,study",
        customInstruction: "Focus on short, highly engaging content under 280 words. Prioritise videos, interactive content, and posts with high viral potential."
    },
    "longform_deep": {
        name: "Longform",
        chronology: 0.2, 
        sentiment: 0,
        variety: 0.8,
        voteImpact: 0.9,
        minWords: 300,
        maxWords: null,
        minVideo: 0,
        maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "analysis,comprehensive,detailed,research,study,investigation,deep,thorough,complete",
        wordSuppress: "quick,brief,summary,tldr,short",
        customInstruction: "Prioritise comprehensive, well-researched longform content. Focus on detailed analysis and thorough investigations. Minimal visual distractions."
    },
    "educational": {
        name: "Educational Content",
        chronology: 0.3,
        sentiment: 0.3,
        variety: 0.9,
        voteImpact: 0.8,
        minWords: 100,
        maxWords: null,
        minVideo: 0,
        maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "tutorial,learn,how-to,guide,explain,education,course,lesson,teach,step-by-step",
        wordSuppress: "clickbait,drama,gossip,celebrity",
        customInstruction: "Focus on educational content with visual aids. Prioritise tutorials, guides, and how-to content with images or interactive elements."
    },
    "entertainment": {
        name: "Entertainment & Fun",
        chronology: 0.6,
        sentiment: 0.6,
        variety: 0.9,
        voteImpact: 0.6,
        minWords: 0,
        maxWords: null,
        minVideo: 0,
        maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "funny,meme,comedy,entertainment,viral,cute,amazing,hilarious,awesome",
        wordSuppress: "serious,political,depressing,sad,tragic",
        customInstruction: "Show entertaining content with positive sentiment. Prioritize funny, cute, and amazing content while filtering out serious or depressing material."
    },
    "professional": {
        name: "Professional Network",
        chronology: 0.8,
        sentiment: 0.2,
        variety: 0.9,
        voteImpact: 0.6,
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "career,professional,industry,business,networking,leadership,startup,innovation,growth",
        wordSuppress: "personal,casual,meme,funny",
        customInstruction: "Focus on professional content. Prioritise career insights, industry news, and business networking content."
    },
    "positive_vibes": {
        name: "Positive Vibes",
        chronology: 0.4,
        sentiment: 0.8,
        variety: 0.9,
        voteImpact: 0.5,
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },    
        wordBoost: "positive,inspiration,motivation,success,achievement,grateful,happiness,love,blessed,amazing",
        wordSuppress: "negative,problem,crisis,drama,toxic,hate,angry,sad,depressing",
        customInstruction: "Show only highly positive, uplifting content. Strongly filter out any negative sentiment or toxic content."
    },
    "tech_innovation": {
        name: "Tech & Innovation",
        chronology: 0.5,
        sentiment: 0.1,
        variety: 0.9,
        voteImpact: 0.7,
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "technology,AI,innovation,startup,coding,software,digital,tech,development,programming",
        wordSuppress: "outdated,legacy,old-school,traditional",
        customInstruction: "Focus on cutting-edge technology and innovation. Prioritise AI, software development, and digital innovation."
    },
    "sports_fitness": {
        name: "Sports & Fitness",
        chronology: 0.5,
        sentiment: 0.3,
        variety: 0.9,
        voteImpact: 0.6,
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "sports,fitness,workout,training,athlete,game,team,health,exercise,gym",
        wordSuppress: "injury,controversy,scandal",
        customInstruction: "Focus on sports and fitness content with visual elements. Prioritise positive athletic content and workout demonstrations."
    },
    "creative_arts": {
        name: "Creative Arts & Culture",
        chronology: 0.5,
        sentiment: 0.4,
        variety: 0.9,
        voteImpact: 0.7,
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "art,creative,design,music,artist,painting,photography,inspiration,culture,aesthetic",
        wordSuppress: "commercial,advertisement,promotion",
        customInstruction: "Show creative and artistic content. Prioritise original art, design inspiration, and cultural content over commercial posts."
    },
    "trending_discussions": {
        name: "Trending Discussions",
        chronology: 0.9, 
        sentiment: 0.1,
        variety: 0.9,
        voteImpact: 0.7, 
		minWords: 0,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "discussion,debate,opinion,thoughts,perspective,community,conversation,trending",
        wordSuppress: "spam,promotional,advertisement",
        customInstruction: "Show highly engaging discussions. Prioritise posts with active comment threads and community engagement."
    },
    "high_quality": {
        name: "High quality",
        chronology: 0.4, 
        sentiment: 0.2,
        variety: 0.7,
        voteImpact: 0.9,
		minWords: 20,
		maxWords: null,
		minVideo: 0,
		maxVideo: null,
        contentType: { images: true, text: true, videos: true, interactive: true },
        wordBoost: "quality,curated,thoughtful,insightful,well-written,informative,valuable",
        wordSuppress: "spam,low-effort,clickbait,rage-bait,toxic",
        customInstruction: "Focus on high-quality, well-crafted content with good engagement. Filter out spam and low-effort posts while prioritising thoughtful, valuable contributions."
    }
};

export { ALGORITHM_TEMPLATES }